sudo: true
before_install:
- wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu && chmod +x ./install-tl-ubuntu
- sudo ./install-tl-ubuntu
- tlmgr install exsheets
- tlmgr install environ
- tlmgr install trimspaces
- tlmgr install cntformats
- tlmgr install cnltx
- tlmgr install pgfopts
- tlmgr install tasks
- tlmgr install epic
script:
- mkdir _build
- pdflatex -output-directory _build tex/test1.tex
- pdflatex -output-directory _build tex/test2.tex
