before_install:
- ./texlive-install.sh
- export PATH="$PATH:$HOME/texlive/bin/x86_64-linux"
- tlmgr install exsheets
- tlmgr install environ
script:
- mkdir _build
- pdflatex -output-directory _build tex/test1.tex
- pdflatex -output-directory _build tex/test2.tex
